### PR TITLE
fixed test related the delete method mode, it seems to happen later than it should

### PR DESCRIPTION
**Pull request by facascante**
fixed the all the test with the new changes

### CODE REVIEW

**Comment by facascante** [comment]
test will be green again 👍

**Comment by alexbeletsky** [comment]
In the code diff, I see only some formating changes.. You closed that PR, because it is invalid?

**Comment by facascante** [comment]
no, i redo the PR to another one that is open, since it's messy changing it always from the github browser

**Comment by facascante** [comment]
by the way it's merge and the test result passed, why the build status still failed?

https://travis-ci.org/likeastore/maintenance

**Pull request closed without merging**
